package vocablint

import (
	"os"
	"path/filepath"
	"testing"
)

func write(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func pad64(seed string) string {
	out := ""
	for len(out) < 64 {
		out += seed
	}
	return out[:64]
}

func validAggregateIR(name string) string {
	return `{
  "kind": "aggregate",
  "name": "` + name + `",
  "slots": [{"name":"id","type":"string","required":true}],
  "source": {"dsl_file": "dsl/x.lisp", "sha256": "` + pad64("a") + `"}
}`
}

func validEventIR(name string) string {
	return `{
  "kind": "event",
  "name": "` + name + `",
  "slots": [{"name":"id","type":"string","required":true}],
  "source": {"dsl_file": "dsl/x.lisp", "sha256": "` + pad64("b") + `"}
}`
}

func TestLoadTermsAggregateAndEvent(t *testing.T) {
	root := t.TempDir()
	irDir := filepath.Join(root, "domain")
	write(t, filepath.Join(irDir, "work-item.ir.json"), validAggregateIR("work-item"))
	write(t, filepath.Join(irDir, "work-item-created.ir.json"), validEventIR("work-item-created"))
	// A query — must NOT contribute to vocablint terms (wirelint owns wire names).
	write(t, filepath.Join(irDir, "list-things.ir.json"), `{
  "kind": "query",
  "name": "list-things",
  "wire_name": "things",
  "returns": {"shape": "list", "type": "work-item"},
  "source": {"dsl_file": "dsl/q.lisp", "sha256": "`+pad64("c")+`"}
}`)
	terms, err := LoadTerms(irDir)
	if err != nil {
		t.Fatal(err)
	}
	if len(terms) != 2 {
		t.Fatalf("expected 2 terms (aggregate + event), got %d (%+v)", len(terms), terms)
	}
	pascals := map[string]bool{}
	for _, term := range terms {
		pascals[term.Pascal] = true
	}
	if !pascals["WorkItem"] || !pascals["WorkItemCreated"] {
		t.Errorf("expected WorkItem + WorkItemCreated, got %v", pascals)
	}
}

func TestScanFlagsGoTypeRedefinition(t *testing.T) {
	root := t.TempDir()
	write(t, filepath.Join(root, "pkg", "x.go"),
		`package pkg

type WorkItem struct {
	ID string
}
`)
	terms := []Term{{Pascal: "WorkItem", Kebab: "work-item", Kind: "aggregate"}}
	found, err := Scan(root, terms, []string{"internal/contracts"})
	if err != nil {
		t.Fatal(err)
	}
	if len(found) != 1 {
		t.Fatalf("expected 1 finding, got %d (%+v)", len(found), found)
	}
	if found[0].Term != "WorkItem" || found[0].Lang != "go" {
		t.Errorf("wrong finding: %+v", found[0])
	}
}

func TestScanFlagsDartClassRedefinition(t *testing.T) {
	root := t.TempDir()
	write(t, filepath.Join(root, "lib", "x.dart"),
		`class WorkItem {
  final String id;
  const WorkItem({required this.id});
}
`)
	terms := []Term{{Pascal: "WorkItem", Kebab: "work-item", Kind: "aggregate"}}
	found, _ := Scan(root, terms, []string{"lib/contracts_client"})
	if len(found) == 0 {
		t.Fatal("expected at least 1 finding (class WorkItem)")
	}
	if found[0].Term != "WorkItem" || found[0].Lang != "dart" {
		t.Errorf("wrong finding: %+v", found[0])
	}
}

func TestScanFlagsAbstractDartClass(t *testing.T) {
	root := t.TempDir()
	write(t, filepath.Join(root, "lib", "x.dart"),
		`abstract class WorkItemRepository {
  WorkItem find(String id);
}
`)
	// Note: this fixture has BOTH "abstract class WorkItemRepository"
	// (should not match — name is WorkItemRepository, not WorkItem) AND
	// "WorkItem find(...)" (function signature, not a class declaration —
	// also should not match). So no findings expected.
	terms := []Term{{Pascal: "WorkItem"}}
	found, _ := Scan(root, terms, nil)
	if len(found) != 0 {
		t.Errorf("expected 0 findings (no exact-name class declaration), got %+v", found)
	}
}

func TestScanSkipsGeneratedFile(t *testing.T) {
	root := t.TempDir()
	write(t, filepath.Join(root, "x.go"),
		`// Code generated by gen-go-client. DO NOT EDIT.
package x

type WorkItem struct {
	ID string
}
`)
	terms := []Term{{Pascal: "WorkItem"}}
	found, _ := Scan(root, terms, nil)
	if len(found) != 0 {
		t.Errorf("expected 0 findings (generated file), got %+v", found)
	}
}

func TestScanSkipsExcludedDir(t *testing.T) {
	root := t.TempDir()
	write(t, filepath.Join(root, "internal", "contracts", "work_item.go"),
		`package contracts

type WorkItem struct {
	ID string
}
`)
	terms := []Term{{Pascal: "WorkItem"}}
	found, _ := Scan(root, terms, []string{"internal/contracts"})
	if len(found) != 0 {
		t.Errorf("expected 0 findings (excluded dir), got %+v", found)
	}
}

func TestScanRespectsIgnoreMarker(t *testing.T) {
	root := t.TempDir()
	write(t, filepath.Join(root, "x_test.go"),
		`package x

type WorkItem struct{} // vocablint:ignore — intentional shadow in tests
`)
	terms := []Term{{Pascal: "WorkItem"}}
	found, _ := Scan(root, terms, nil)
	if len(found) != 0 {
		t.Errorf("expected 0 findings (ignore marker), got %+v", found)
	}
}

func TestScanIgnoresPartialMatches(t *testing.T) {
	root := t.TempDir()
	write(t, filepath.Join(root, "x.go"),
		`package x

type WorkItemBuilder struct{}
type WorkItemHelper struct{}
type SomethingElse struct{}
var workItem int   // lowercase — must not match
`)
	terms := []Term{{Pascal: "WorkItem"}}
	found, _ := Scan(root, terms, nil)
	if len(found) != 0 {
		t.Errorf("expected 0 findings (no exact match), got %+v", found)
	}
}

func TestScanEmptyTermsNoOp(t *testing.T) {
	root := t.TempDir()
	write(t, filepath.Join(root, "x.go"), `package x
type WorkItem struct{}`)
	found, err := Scan(root, nil, nil)
	if err != nil {
		t.Fatal(err)
	}
	if len(found) != 0 {
		t.Errorf("expected 0 findings when terms is empty, got %+v", found)
	}
}

func TestScanCatchesInterfaceAndAlias(t *testing.T) {
	root := t.TempDir()
	write(t, filepath.Join(root, "iface.go"),
		`package x
type WorkItem interface { Title() string }
`)
	write(t, filepath.Join(root, "alias.go"),
		`package x
type WorkItem = int
`)
	terms := []Term{{Pascal: "WorkItem"}}
	found, _ := Scan(root, terms, nil)
	if len(found) != 2 {
		t.Errorf("expected 2 findings (interface + alias), got %d (%+v)", len(found), found)
	}
}
