package wirelint

import (
	"os"
	"path/filepath"
	"testing"
)

func write(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

// validQueryIR returns a minimal kind=query IR document with the given
// wire_name. Used to populate ir/domain/ for tests.
func validQueryIR(name, wire string) string {
	return `{
  "kind": "query",
  "name": "` + name + `",
  "wire_name": "` + wire + `",
  "returns": {"shape": "list", "type": "work-item"},
  "source": {
    "dsl_file": "dsl/domain/` + name + `.lisp",
    "sha256": "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
  }
}`
}

func TestLoadWiresEmptyIRDir(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "domain"), 0o755); err != nil {
		t.Fatal(err)
	}
	wires, err := LoadWires(filepath.Join(root, "domain"))
	if err != nil {
		t.Fatal(err)
	}
	if len(wires) != 0 {
		t.Errorf("expected no wires, got %v", wires)
	}
}

func TestLoadWiresOnlyQueryKind(t *testing.T) {
	root := t.TempDir()
	irDir := filepath.Join(root, "domain")
	write(t, filepath.Join(irDir, "list-things.ir.json"), validQueryIR("list-things", "things"))
	// An aggregate doc — must be ignored.
	write(t, filepath.Join(irDir, "thing.ir.json"), `{
  "kind": "aggregate", "name": "thing",
  "slots": [{"name":"id","type":"string","required":true}],
  "source": {"dsl_file": "dsl/x.lisp", "sha256": "`+pad64("a")+`"}
}`)
	wires, err := LoadWires(irDir)
	if err != nil {
		t.Fatal(err)
	}
	if len(wires) != 1 {
		t.Fatalf("expected 1 wire, got %d (%v)", len(wires), wires)
	}
	if wires[0].Name != "things" {
		t.Errorf("wire = %q", wires[0].Name)
	}
}

func pad64(seed string) string {
	out := ""
	for len(out) < 64 {
		out += seed
	}
	return out[:64]
}

func TestScanFlagsLiteralInUnallowedFile(t *testing.T) {
	root := t.TempDir()
	write(t, filepath.Join(root, "internal", "slice", "server.go"),
		`package slice
const q = "workItems"
`)
	wires := []Wire{{Name: "workItems", IRPath: "ir/domain/list-work-items.ir.json", IRDocName: "list-work-items"}}
	found, err := Scan(root, wires, []string{"internal/contracts"})
	if err != nil {
		t.Fatal(err)
	}
	if len(found) != 1 {
		t.Fatalf("expected 1 finding, got %d: %+v", len(found), found)
	}
	if found[0].Wire != "workItems" || found[0].Line != 2 {
		t.Errorf("finding wrong: %+v", found[0])
	}
}

func TestScanSkipsGeneratedFile(t *testing.T) {
	root := t.TempDir()
	write(t, filepath.Join(root, "internal", "slice", "generated.go"),
		`// Code generated by gen-go-client. DO NOT EDIT.
//
// (intentionally outside the excluded dir to prove header detection works)
package slice
const q = "workItems"
`)
	wires := []Wire{{Name: "workItems"}}
	found, _ := Scan(root, wires, nil)
	if len(found) != 0 {
		t.Errorf("expected 0 findings (generated file should be skipped), got %d: %+v", len(found), found)
	}
}

func TestScanSkipsExcludedDir(t *testing.T) {
	root := t.TempDir()
	write(t, filepath.Join(root, "internal", "contracts", "list_work_items.go"),
		`package contracts
const ListWorkItemsQueryName = "workItems"
`)
	wires := []Wire{{Name: "workItems"}}
	found, _ := Scan(root, wires, []string{"internal/contracts"})
	if len(found) != 0 {
		t.Errorf("expected 0 findings (excluded dir), got %+v", found)
	}
}

func TestScanRespectsWirelintIgnoreLineMarker(t *testing.T) {
	root := t.TempDir()
	write(t, filepath.Join(root, "doc.md"),
		`See the wire string "workItems" for context. // wirelint:ignore
`)
	wires := []Wire{{Name: "workItems"}}
	found, _ := Scan(root, wires, nil)
	if len(found) != 0 {
		t.Errorf("expected 0 findings (line ignored), got %+v", found)
	}
}

func TestScanEmptyWiresNoOp(t *testing.T) {
	root := t.TempDir()
	write(t, filepath.Join(root, "anything.go"), `const x = "workItems"`)
	found, err := Scan(root, nil, nil)
	if err != nil {
		t.Fatal(err)
	}
	if len(found) != 0 {
		t.Errorf("expected 0 findings when wires is empty, got %+v", found)
	}
}

func TestScanMatchesBothQuoteStyles(t *testing.T) {
	root := t.TempDir()
	write(t, filepath.Join(root, "x.dart"),
		`var q = 'workItems';
var p = "workItems";
`)
	wires := []Wire{{Name: "workItems"}}
	found, _ := Scan(root, wires, nil)
	if len(found) != 2 {
		t.Errorf("expected 2 findings (both quote styles), got %d: %+v", len(found), found)
	}
}

func TestScanIgnoresIdentifierLikeOccurrence(t *testing.T) {
	root := t.TempDir()
	// Unquoted identifier — not a string literal, should NOT match.
	write(t, filepath.Join(root, "x.go"),
		`package x
const workItems = 1
`)
	wires := []Wire{{Name: "workItems"}}
	found, _ := Scan(root, wires, nil)
	if len(found) != 0 {
		t.Errorf("expected 0 findings (identifier, not string literal), got %+v", found)
	}
}
