// gen-go-client: read ir/domain/*.ir.json from a contracts checkout and emit
// one Go source file per aggregate/event into --out-dir. The emitted files are
// the canonical generated-client artifacts consumed by agent-cluster-backend.
//
// Usage:
//   gen-go-client [--ir-dir contracts/ir/domain] [--out-dir backend/internal/contracts] [--package contracts]
//
// Output is deterministic (sorted by IR Name, no timestamps, tab-indented per
// gofmt). A drift workflow regenerates into a temp dir and diffs against the
// committed files.
package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/kimjooyoon/agent-cluster-contracts/internal/codegen"
	"github.com/kimjooyoon/agent-cluster-contracts/internal/findroot"
)

func main() {
	defaultIR := ""
	if root, err := findroot.FromCWDOrEnv(); err == nil {
		defaultIR = filepath.Join(root, "ir", "domain")
	}
	irDir := flag.String("ir-dir", defaultIR, "directory containing *.ir.json files")
	outDir := flag.String("out-dir", "", "directory to write generated Go files into (required)")
	pkg := flag.String("package", "contracts", "Go package name for generated files")
	flag.Parse()
	if *outDir == "" {
		fmt.Fprintln(os.Stderr, "--out-dir is required")
		os.Exit(2)
	}
	if *irDir == "" {
		fmt.Fprintln(os.Stderr, "--ir-dir is required (could not auto-detect contracts root)")
		os.Exit(2)
	}
	docs, err := codegen.LoadAll(*irDir)
	if err != nil {
		fmt.Fprintln(os.Stderr, "load IR:", err)
		os.Exit(1)
	}
	if err := os.MkdirAll(*outDir, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "mkdir out-dir:", err)
		os.Exit(1)
	}
	for _, d := range docs {
		path := filepath.Join(*outDir, codegen.FileBase(d.Name)+".go")
		raw := emit(d, *pkg)
		formatted, err := format.Source([]byte(raw))
		if err != nil {
			fmt.Fprintln(os.Stderr, "gofmt", path+":", err)
			fmt.Fprintln(os.Stderr, "--- raw ---")
			fmt.Fprintln(os.Stderr, raw)
			os.Exit(1)
		}
		if err := os.WriteFile(path, formatted, 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "write", path+":", err)
			os.Exit(1)
		}
		fmt.Println("wrote", path)
	}
}

func emit(d *codegen.IRDoc, pkg string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by gen-go-client. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// IR source: %s\n", d.Source.DSLFile)
	fmt.Fprintf(&b, "// IR sha256: %s\n", d.Source.SHA256)
	fmt.Fprintf(&b, "// IR kind:   %s\n\n", d.Kind)
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	typeName := codegen.Pascal(d.Name)

	switch d.Kind {
	case "aggregate", "event":
		fmt.Fprintf(&b, "type %s struct {\n", typeName)
		for _, s := range d.Slots {
			fmt.Fprintf(&b, "\t%s %s `json:%q`\n", codegen.Pascal(s.Name), goTypeFor(s.Type), codegen.Snake(s.Name))
		}
		fmt.Fprintf(&b, "}\n")
		if d.Kind == "event" {
			fmt.Fprintf(&b, "\n// %sEventName is the wire identifier emitted in SSE payloads for %s.\n", typeName, typeName)
			fmt.Fprintf(&b, "const %sEventName = %q\n", typeName, d.Name)
		}
	case "query":
		// Decision 006: queries emit a wire-name const and a result-type
		// alias. Backend must use these constants instead of hand-typing
		// the wire identifier or the result shape (constraint C-006).
		fmt.Fprintf(&b, "// %sQueryName is the GraphQL wire identifier for the %s query.\n",
			typeName, d.Name)
		fmt.Fprintf(&b, "const %sQueryName = %q\n", typeName, d.WireName)
		if d.Returns != nil {
			retType := codegen.Pascal(d.Returns.Type)
			switch d.Returns.Shape {
			case "list":
				fmt.Fprintf(&b, "\n// %sResult is the result element collection for the %s query.\n",
					typeName, d.Name)
				fmt.Fprintf(&b, "type %sResult = []%s\n", typeName, retType)
			case "one":
				fmt.Fprintf(&b, "\n// %sResult is the result type for the %s query.\n",
					typeName, d.Name)
				fmt.Fprintf(&b, "type %sResult = %s\n", typeName, retType)
			}
		}
	default:
		fmt.Fprintf(&b, "// gen-go-client: unsupported IR kind %q for %s\n", d.Kind, d.Name)
	}
	return b.String()
}

func goTypeFor(irType string) string {
	switch irType {
	case "string":
		return "string"
	case "int", "integer":
		return "int64"
	case "bool", "boolean":
		return "bool"
	default:
		// Unknown types are left as the IR token, prefixed with a comment so
		// drift is visible if someone introduces a new type without extending
		// this generator (which requires a decision record).
		return "any /* unknown IR type: " + irType + " */"
	}
}
