// gen-dart-client: read ir/domain/*.ir.json and emit one Dart source file per
// aggregate/event into --out-dir. The emitted files are the canonical
// generated-client artifacts consumed by agent-cluster-frontend.
//
// Output is deterministic: sorted by IR Name, no timestamps, two-space indent
// (Dart convention).
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/kimjooyoon/agent-cluster-contracts/internal/codegen"
	"github.com/kimjooyoon/agent-cluster-contracts/internal/findroot"
)

func main() {
	defaultIR := ""
	if root, err := findroot.FromCWD(); err == nil {
		defaultIR = filepath.Join(root, "ir", "domain")
	}
	irDir := flag.String("ir-dir", defaultIR, "directory containing *.ir.json files")
	outDir := flag.String("out-dir", "", "directory to write generated Dart files into (required)")
	flag.Parse()
	if *outDir == "" {
		fmt.Fprintln(os.Stderr, "--out-dir is required")
		os.Exit(2)
	}
	if *irDir == "" {
		fmt.Fprintln(os.Stderr, "--ir-dir is required (could not auto-detect contracts root)")
		os.Exit(2)
	}
	docs, err := codegen.LoadAll(*irDir)
	if err != nil {
		fmt.Fprintln(os.Stderr, "load IR:", err)
		os.Exit(1)
	}
	if err := os.MkdirAll(*outDir, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "mkdir out-dir:", err)
		os.Exit(1)
	}
	for _, d := range docs {
		path := filepath.Join(*outDir, codegen.FileBase(d.Name)+".dart")
		content := emit(d)
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "write", path+":", err)
			os.Exit(1)
		}
		fmt.Println("wrote", path)
	}
}

func emit(d *codegen.IRDoc) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by gen-dart-client. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// IR source: %s\n", d.Source.DSLFile)
	fmt.Fprintf(&b, "// IR sha256: %s\n", d.Source.SHA256)
	fmt.Fprintf(&b, "// IR kind:   %s\n\n", d.Kind)

	className := codegen.Pascal(d.Name)
	// Class declaration
	fmt.Fprintf(&b, "class %s {\n", className)
	for _, s := range d.Slots {
		fmt.Fprintf(&b, "  final %s %s;\n", dartTypeFor(s.Type), codegen.Camel(s.Name))
	}

	// Const constructor
	fmt.Fprintf(&b, "\n  const %s({\n", className)
	for _, s := range d.Slots {
		fmt.Fprintf(&b, "    required this.%s,\n", codegen.Camel(s.Name))
	}
	fmt.Fprintf(&b, "  });\n")

	// fromJson
	fmt.Fprintf(&b, "\n  factory %s.fromJson(Map<String, dynamic> json) => %s(\n", className, className)
	for _, s := range d.Slots {
		fmt.Fprintf(&b, "        %s: json[%q] as %s,\n", codegen.Camel(s.Name), codegen.Snake(s.Name), dartTypeFor(s.Type))
	}
	fmt.Fprintf(&b, "      );\n")

	// toJson
	fmt.Fprintf(&b, "\n  Map<String, dynamic> toJson() => {\n")
	for _, s := range d.Slots {
		fmt.Fprintf(&b, "        %q: %s,\n", codegen.Snake(s.Name), codegen.Camel(s.Name))
	}
	fmt.Fprintf(&b, "      };\n")

	fmt.Fprintf(&b, "}\n")

	if d.Kind == "event" {
		fmt.Fprintf(&b, "\n/// Wire identifier emitted in SSE payloads for [%s].\n", className)
		fmt.Fprintf(&b, "const String %sEventName = %q;\n", codegen.Camel(d.Name), d.Name)
	}
	return b.String()
}

func dartTypeFor(irType string) string {
	switch irType {
	case "string":
		return "String"
	case "int", "integer":
		return "int"
	case "bool", "boolean":
		return "bool"
	default:
		return "Object /* unknown IR type: " + irType + " */"
	}
}
